spring:
    datasource:
        driverClassName: org.postgresql.Driver
        initialSize: 5
        maxActive: 10
        maxIdle: 5
        minIdle: 2
        removeAbandoned: true
        url: ${JDBC_DATABASE_URL}
security:
  oauth2:
    client:
      clientId: dj0yJmk9NzQ4YXhRaDhNYVB1JmQ9WVdrOVRqSkdaVzFzTjJVbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD0xNQ--
      clientSecret: 995b3dcab0c7e5d4b5375b3b7b9185c9736563e9
      accessTokenUri: https://api.login.yahoo.com/oauth2/get_token
      userAuthorizationUri: https://api.login.yahoo.com/oauth2/request_auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: